@startuml

title __HUMAN_EXAMPLE's Class Diagram__\n

  namespace  {
    namespace com.abolfazl.human_example {
      class com.abolfazl.human_example.Actor {
          {static} ~ LIFESPAN : int
          - actingSchool : String
          - age : int
          - films : List<String>
          - height : float
          - name : String
          + Actor()
          + getActingSchool()
          + getAge()
          + getFilms()
          + getHeight()
          + getName()
          + getTimeToLive()
          + setActingSchool()
          + setAge()
          + setFilms()
          + setHeight()
          + setName()
      }
    }
  }
  

  namespace  {
    namespace om.abolfazl.human_example {
      abstract class com.abolfazl.human_example.Human {
          {static} ~ LIFESPAN : int
          - age : int
          - height : float
          - name : String
          + Human()
          + Human()
          + getAge()
          + getHeight()
          + getName()
          {abstract} + getTimeToLive()
          + setAge()
          + setHeight()
          + setName()
      }
    }
  }
  

  namespace  {
    namespace om.abolfazl.human_example {
      class com.abolfazl.human_example.Main {
          {static} + main()
      }
    }
  }
  

  namespace  {
    namespace om.abolfazl.human_example {
      class com.abolfazl.human_example.Musician {
          {static} ~ LIFESPAN : int
          - age : int
          - genre : String
          - height : float
          - musicSchool : String
          - name : String
          - songs : List<String>
          + Musician()
          + getAge()
          + getGenre()
          + getHeight()
          + getMusicSchool()
          + getName()
          + getSongs()
          + getTimeToLive()
          + setAge()
          + setGenre()
          + setHeight()
          + setMusicSchool()
          + setName()
          + setSongs()
      }
    }
  }
  

  com.abolfazl.human_example.Actor -up-|> com.abolfazl.human_example.Human
  com.abolfazl.human_example.Musician -up-|> com.abolfazl.human_example.Human


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
